### ISSUE TITLE
Metamask extensions makes the verify fail

### ISSUE THREAD

**Issue by Theagainmen** [facebookincubator/meta-code-verify#139]
Hello all,

Just installed this extension and noticed I got a failure, I did some reading on the wapp FAQ and they suggested to disable some of your extensions and re-check. I disabled my extensions and figured out Metamask (https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn, a crypto wallet extension) was causing it to fail.

Could anyone else try and verify this. And should I be worried about it, or does it not matter? Metamask is widely used as a crypto wallet among many (over 10 million installations) users. 

Thanks for any help :)

**Comment by rich-hansen** [comment]
So, Metamask inserts some script into the page, that script doesn't come from WhatsApp, which is why it's triggering the verification failure. Should you be worried about it? It's hard for me to say without analyzing their code. If you install the extension you're trusting it to some degree. If it would make you feel better you could disable it for the WhatsApp page if you're not using it there, which would stop the error from triggering.

If I recall correctly the script it inserts is different every time, so I wouldn't be able to add it to the allowlist.

**Comment by Theagainmen** [comment]
Thank you, that makes sense. Do you know how I can disable Metamask from running on the WhatsApp page? I can't find it in the extension settings
